# Generated by Django 3.0.4 on 2020-03-19 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=10)),
                ('phone1', models.CharField(max_length=10)),
                ('phone2', models.CharField(max_length=10, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('policygroup', models.CharField(max_length=30)),
                ('policynumber', models.CharField(max_length=30)),
                ('policyname', models.CharField(max_length=100, null=True)),
                ('policydob', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Practioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_firstname', models.CharField(max_length=50)),
                ('dr_lastname', models.CharField(max_length=50)),
                ('dr_address1', models.CharField(max_length=50)),
                ('dr_address2', models.CharField(max_length=50, null=True)),
                ('dr_city', models.CharField(max_length=30)),
                ('dr_state', models.CharField(max_length=2)),
                ('dr_zipcode', models.CharField(max_length=10)),
                ('dr_phone1', models.CharField(max_length=10)),
                ('dr_phone2', models.CharField(max_length=10, null=True)),
                ('npi', models.CharField(max_length=10, unique=True)),
                ('patients', models.ManyToManyField(related_name='practioner', to='apiapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='ICD10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd10', models.CharField(max_length=10)),
                ('agediagnosis', models.IntegerField()),
                ('relationship', models.CharField(max_length=20, null=True)),
                ('sidefamily', models.CharField(choices=[('M', 'Mother'), ('F', 'Father')], max_length=1, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icd10s', to='apiapp.Patient')),
            ],
        ),
    ]
