# Generated by Django 3.0.4 on 2020-03-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='lookupnpi',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
